trigger: none

pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
    displayName: 'Use Yarn 1.19.x'
    inputs:
      versionSpec: 1.19.x
      checkLatest: true
      includePrerelease: false

  - script: yarn
    displayName: yarn install

  - script: yarn build
    displayName: Build

  - task: AzureFileCopy@3
    displayName: 'AzureBlob File Copy'
    inputs:
      SourcePath: packages/fabric-website/public
      azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'
      Destination: AzureBlob
      storage: fabsite
      ContainerName: '$web'
