backend:
  name: github
  repo: kenotron/fabsite
  branch: master
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets
collections:
  - name: components
    extension: mdx
    format: frontmatter
    label: Components
    folder: packages/fabric-website/content/components
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: overview, label: overview, widget: markdown }
      - { name: layout, label: layout, widget: markdown, required: false }
      - { name: content, label: content, widget: markdown, required: false }
      - {
          name: accessibility,
          label: accessibility,
          widget: markdown,
          required: false,
        }
      - {
          name: globalization,
          label: globalization,
          widget: markdown,
          required: false,
        }
      - { name: behavior, label: behavior, widget: markdown, required: false }
      - {
          name: examples,
          label: Examples,
          widget: list,
          fields:
            [
              { name: title, label: Title },
              { name: image, label: Image, widget: image },
            ],
        }
  - label: Pages
    name: pages
    extension: mdx
    format: frontmatter
    create: true
    folder: packages/fabric-website/src/pages
    fields:
      - { name: title, label: Title }
      - {
          label: Content,
          name: content,
          widget: list,
          fields:
            [
              { label: Name, name: name, widget: string },
              { label: Copy, name: copy, widget: markdown },
            ],
        }
  - name: dog
    label: Dog
    create: true
    folder: packages/fabric-website/content/dogs
    fields:
      - { name: title, lable: Name }
      - { name: breed, lable: Breed }
      - { name: cute, lable: Cute, widget: boolean }
      - { name: photo, lable: Photo, widget: image }
