backend:
  name: github
  repo: kenotron/fabsite
  branch: master

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: components
    extension: "mdx"
    format: "frontmatter"
    label: Components
    folder: packages/fabric-website/content/components
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Overview, widget: markdown }
      - label: Content
        name: content
        widget: list
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Copy, name: copy, widget: markdown }
  - label: "Pages"
    name: "pages"
    extension: "mdx"
    format: "frontmatter"
    folder: packages/fabric-website/src/pages
    fields:
      - { name: title, label: Title }
      - { name: body, label: Overview, widget: markdown }
