backend:
  name: github
  repo: kenotron/fabsite
  branch: master

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: components
    extension: mdx
    format: frontmatter
    label: Components
    folder: packages/fabric-website/content/components
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: overview, label: overview, widget: fabricmarkdown }
      - { name: layout, label: layout, widget: fabricmarkdown }
      - { name: content, label: content, widget: fabricmarkdown }
      - { name: accessibility, label: accessibility, widget: fabricmarkdown }
      - { name: globalization, label: globalization, widget: fabricmarkdown }
      - { name: behavior, label: behavior, widget: fabricmarkdown }
      - name: examples
        label: Examples
        widget: list
        fields:
          - { name: title, label: Title }
          - { name: image, label: Image, widget: image }
  - label: Pages
    name: pages
    extension: mdx
    format: frontmatter
    create: true
    folder: packages/fabric-website/src/pages
    fields:
      - { name: title, label: Title }
      - label: Content
        name: content
        widget: list
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Copy, name: copy, widget: fabricmarkdown }
  - label: People
    name: people
    folder: packages/fabric-website/content/people
    fields:
      - { name: name, lable: Name }
      - { name: title, lable: Title }
      - { name: color, lable: Favorite Color }
