backend:
  name: github
  repo: kenotron/fabsite
  branch: master

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: components
    extension: "mdx"
    format: "frontmatter"
    label: Components
    folder: packages/fabric-website/content/components
    create: true
    fields:
      - { name: title, label: Title }
      - { name: title, label: Title }
      - { name: body, label: Overview, widget: markdown }
      - {
          name: dos,
          label: Dos,
          widget: list,
          field: { label: Do, name: do, widget: string },
        }
      - {
          name: donts,
          label: Donts,
          widget: list,
          field: { label: Dont, name: dont, widget: string },
        }
      - name: implementation
        label: Implementation
        widget: list
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Image, name: image, widget: image }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Get Started"
        name: "started"
        extension: "mdx"
        format: "frontmatter"
        file: "packages/fabric-website/src/pages/index.mdx"
        fields:
          - { name: body, label: Body, widget: markdown }
      - label: "Resources"
        name: "resources"
        extension: "mdx"
        format: "frontmatter"
        file: "packages/fabric-website/src/pages/resources.mdx"
        fields:
          - { name: body, label: Body, widget: markdown }
      - label: "Test"
        name: "test"
        extension: "mdx"
        format: "frontmatter"
        file: "packages/fabric-website/src/pages/test.mdx"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
